<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Barryvdh\DomPDF\Facade\Pdf;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;

class ReportController extends Controller
{
    public function export(Request $request)
    {
        $format = $request->query('format', 'pdf');
        $fileName = "Procurement_Report_" . date('Y-m-d') .
            (
                $format === 'excel'
                ? '.xlsx'
                : ($format === 'docx'
                    ? '.docx'
                    : '.pdf')
            );
        $stats = [
            'generated_by' => 'Johnny (IT Personnel)',
            'date_range' => 'June 01 - June 30, 2026',
            'generated_at' => now()->format('F d, Y h:i A'),
            'total_spending' => 'PHP 30,910.00',
            'departments' => [
                ['name' => 'IT Department', 'spent' => 12450, 'budget' => 20000, 'pct' => '62.25%'],
                ['name' => 'Human Resources', 'spent' => 4120, 'budget' => 10000, 'pct' => '41.20%'],
                ['name' => 'Marketing', 'spent' => 8900, 'budget' => 15000, 'pct' => '59.30%'],
                ['name' => 'Finance', 'spent' => 5440, 'budget' => 10000, 'pct' => '54.40%'],
            ],
            'suppliers' => [
                ['name' => 'ICTO Corp.', 'delivery' => '95.4%', 'quality' => '4.6/5', 'score' => '92% Outstanding'],
                ['name' => 'Starlink', 'delivery' => '94.1%', 'quality' => '3.6/5', 'score' => '90% Verified'],
                ['name' => 'ACER', 'delivery' => '95.0%', 'quality' => '3.6/5', 'score' => '94% Outstanding'],
            ]
        ];

        // 2. HANDLE EXCEL (Formatted as a clean Tab-Separated Table)
        if ($format === 'excel') {
            $output = "Procurement Report\nGenerated at: {$stats['generated_at']}\n\n";
            $output .= "Department\tSpent\tUsage\n";
            foreach ($stats['departments'] as $d) {
                $output .= "{$d['name']}\t{$d['spent']}\t{$d['pct']}\n";
            }
            return response($output)
                ->header('Content-Type', 'application/vnd.ms-excel')
                ->header('Content-Disposition', "attachment; filename={$fileName}");
        }

        // 3. GENERATE SHARED HTML CONTENT (For PDF & Word)
        $htmlContent = $this->generateHtmlReport($stats);

        // 4. DOWNLOAD WORD OR PDF
        // Replace your existing docx block in ReportController.php with this:

if ($format === 'docx') {
    $phpWord = new PhpWord();
    $section = $phpWord->addSection();
    
    $section->addText("Official Procurement Report", ['bold' => true, 'size' => 16]);
    $section->addText("Generated by: {$stats['generated_by']} | {$stats['date_range']}");
    $section->addTextBreak(1);

    $section->addText("Departmental Spending", ['bold' => true, 'size' => 14]);
    $table = $section->addTable();
    
    foreach ($stats['departments'] as $d) {
        $table->addRow();
        $table->addCell(4000)->addText($d['name']);
        $table->addCell(2000)->addText("PHP " . number_format($d['spent']));
        $table->addCell(2000)->addText($d['pct']);
    }

    $fileName = "Procurement_Report_" . date('Y-m-d') . ".docx";
    
    // Save to a temporary stream instead of storage_path
    $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
    
    header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    header('Content-Disposition: attachment;filename="' . $fileName . '"');
    header('Cache-Control: max-age=0');
    
    $objWriter->save('php://output');
    exit; 
}

        $pdf = App::make('dompdf.wrapper');
        $pdf->setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true]);
        $pdf->loadHTML($htmlContent);
        return $pdf->download($fileName);
    }

    private function generateHtmlReport($stats)
    {
        // Use this structure for consistent look in PDF and Word
        return "
        <html>
        <head>
            <style>
                body { font-family: sans-serif; font-size: 12px; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                th { background: #f4f4f4; padding: 10px; border: 1px solid #ccc; text-align: left; }
                td { padding: 8px; border: 1px solid #ccc; }
                h2 { color: #0F172A; border-bottom: 2px solid #00B67A; padding-bottom: 5px; }
            </style>
        </head>
        <body>
            <h1>Official Procurement Report</h1>
            <p>Generated by: {$stats['generated_by']} | {$stats['date_range']}</p>
            
            <h2>Departmental Spending</h2>
            <table>
                <tr><th>Department</th><th>Amount Spent</th><th>Budget Usage</th></tr>
                " . implode('', array_map(fn($d) => "<tr><td>{$d['name']}</td><td>PHP " . number_format($d['spent']) . "</td><td>{$d['pct']}</td></tr>", $stats['departments'])) . "
            </table>

            <h2>Supplier Performance</h2>
            <table>
                <tr><th>Supplier</th><th>Delivery Rate</th><th>Score</th></tr>
                " . implode('', array_map(fn($s) => "<tr><td>{$s['name']}</td><td>{$s['delivery']}</td><td>{$s['score']}</td></tr>", $stats['suppliers'])) . "
            </table>
        </body>
        </html>";
    }
}